FROM node:latest
RUN apk add --no-cache nginx
WORKDIR /app
COPY package.json .
RUN yarn install
ADD misc/nginx.default /etc/nginx/conf.d/default.conf
ADD misc/nginx.conf /etc/nginx/nginx.conf
COPY . .
RUN npm run build
EXPOSE 80
CMD ["nginx"]
