#==================== Building Stage ================================================

# Create the image based on the official Node 8.9.0 image from Dockerhub
FROM node:latest

# Create a directory where our app will be placed. This might not be necessary
RUN mkdir -p /proyecto

# Change directory so that our commands run inside this new directory
WORKDIR /to-do-app

# Copy dependency definitions
COPY package.json /proyecto

# Install dependencies using npm
RUN npm install

# Get all the code needed to run the app
COPY . /proyecto

# Expose the port the app runs in
EXPOSE 4200

#Build the app
RUN npm run build

#==================== Setting up stage ====================
# Create image based on the official nginx - Alpine image
FROM nginx:latest

COPY --from=node /proyecto/dist/ /usr/share/nginx/html

COPY ./nginx-to-do-app.conf /etc/nginx/conf.d/default.conf
